create table public.products (
  id uuid not null default gen_random_uuid (),
  name text not null,
  sku text null,
  description text null,
  category_id uuid null,
  supplier_id uuid null,
  brand text null,
  cost_price numeric(10, 2) null,
  selling_price numeric(10, 2) null,
  unit text null,
  status text null default 'draft'::text,
  image_url text null,
  additional_images text[] null,
  tax_rate numeric(5, 2) null,
  barcode text null,
  discount jsonb null,
  organization_id uuid not null,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  has_variations boolean null default false,
  branch_id uuid null,
  constraint products_pkey primary key (id),
  constraint products_branch_id_fkey foreign KEY (branch_id) references branches (id) on delete set null,
  constraint products_category_id_fkey foreign KEY (category_id) references product_categories (id) on delete set null,
  constraint products_supplier_id_fkey foreign KEY (supplier_id) references suppliers (id) on delete set null
) TABLESPACE pg_default;
